apiVersion: v1
kind: Service
metadata:
  name: spring-petclinic-service
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.appName }}
    tier: {{ .Values.appTier }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: {{ .Values.appName }}
    tier: {{ .Values.appTier }}
