apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.appName }}
    tier: {{ .Values.appTier }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.appName }}
      tier: {{ .Values.appTier }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
        tier: {{ .Values.appTier }}
    spec:
      containers:
        - name: {{ .Values.appName }}
          image: "{{ .Values.image.name }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 8080
