name: Deploy to Kubernetes

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      REGISTRY_URL: "registry.salapie.com"
      IMAGE_NAME: "admin/spring-petclinic"
      IMAGE_TAG: "1.0.0"

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Registry
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin $REGISTRY_URL

      - name: Build Docker image
        run: docker build -t $REGISTRY_URL/$IMAGE_NAME:$IMAGE_TAG .

      - name: Push Docker image
        run: docker push $REGISTRY_URL/$IMAGE_NAME:$IMAGE_TAG

      - name: Set up kubectl
        uses: azure/k8s-set-context@v1
        with:
          kubeconfig: ${{secrets.KUBE_CONFIG_DATA}}

      - name: Install Helm
        uses: azure/setup-helm@v4.1.0

      - name: Deploy to Kubernetes
        run: |
          helm upgrade --install spring-petclinic-release-dev ./helm/ --values ./helm/values.yaml -f ./helm/values-dev.yaml -n dev
